"""Build service/src/utils/chinese_script_data.ts from OpenCC's dictionaries (#97).

The Worker's translator (Workers AI m2m100) only writes Simplified Chinese, so
a Traditional target is reached by converting its output with OpenCC's tables.
Only what a conversion needs is kept: the first candidate for each character,
and the phrases whose conversion differs from converting them character by
character (OpenCC's own longest-match rule then picks them).

Usage (OpenCC data at a pinned commit, Apache-2.0):
    python scripts/build_chinese_script_data.py <opencc data/dictionary dir> <commit>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "service" / "src" / "utils" / "chinese_script_data.ts"


def read_table(path: Path) -> dict[str, str]:
    table: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        source, _, targets = line.partition("\t")
        first = targets.split(" ")[0].strip()
        if source and first and source not in table:
            table[source] = first
    return table


def by_character(text: str, characters: dict[str, str]) -> str:
    return "".join(characters.get(char, char) for char in text)


def useful_phrases(phrases: dict[str, str], characters: dict[str, str]) -> dict[str, str]:
    return {
        source: target
        for source, target in phrases.items()
        if len(source) > 1 and by_character(source, characters) != target
    }


def changed_only(table: dict[str, str]) -> dict[str, str]:
    return {source: target for source, target in table.items() if source != target}


def main() -> None:
    data_dir = Path(sys.argv[1])
    commit = sys.argv[2]
    s2t_chars = read_table(data_dir / "STCharacters.txt")
    t2s_chars = read_table(data_dir / "TSCharacters.txt")
    tables = {
        "S2T_CHARACTERS": changed_only(s2t_chars),
        "S2T_PHRASES": useful_phrases(read_table(data_dir / "STPhrases.txt"), s2t_chars),
        "T2S_CHARACTERS": changed_only(t2s_chars),
        "T2S_PHRASES": useful_phrases(read_table(data_dir / "TSPhrases.txt"), t2s_chars),
        "TW_VARIANTS": changed_only(read_table(data_dir / "TWVariants.txt")),
        "HK_VARIANTS": changed_only(read_table(data_dir / "HKVariants.txt")),
    }
    lines = [
        "// Generated by scripts/build_chinese_script_data.py. Do not edit by hand.",
        f"// Source: OpenCC data/dictionary at BYVoid/OpenCC@{commit}",
        "// (https://github.com/BYVoid/OpenCC), Apache License 2.0.",
        "",
    ]
    for name, table in tables.items():
        encoded = json.dumps(dict(sorted(table.items())), ensure_ascii=False, separators=(",", ":"))
        lines.append(f"export const {name}: Readonly<Record<string, string>> = {encoded};")
        lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    for name, table in tables.items():
        print(f"{name}: {len(table)}")
    print(f"{OUTPUT.relative_to(REPO_ROOT)}: {OUTPUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
